### ISSUE TITLE
Missing access control at backend

### ISSUE THREAD

**Issue by Amrit-Pal-Singh-3103** [Akansh97/twitch-predcon-v1#1]
You must add validation in backend that only admin can perform certain things like create poll and update scores.
In current code anyone can create poll and update scores from applications like postman.

**Comment by Akansh97** [comment]
Thanks for looking into the code.

This is not the latest build.

Added validation in backend in live version, will update here after final build. 

If you came here from BB17 prediction, please go ahead and let me know if you find any vulnerability on Discord at 1_catalyst_1 (Aka_Stark), I'll be happy to collaborate !! 

Looking forward to hearing from you ✌️

**Comment by Amrit-Pal-Singh-3103** [comment]
Okay✌️
